Tanna\UserBundle\Model\Group:
    type: mappedSuperclass
    fields:
        name:
            type: string
            length: 255

        description:
            type: text

        roles:
            type: array
